site_name: Azure AI Bites
nav:
- Introduction: index.md
- Setting up model deployment in Azure AI Foundry: recipe_2_getting_started_ai_foundry.md
- Basic Chat Completion: recipe_3_basic_chat.md
- Migrate to Azure Inference Chat Completion: recipe_4_migrating.md
- Generate an Sales by Region Pie Chart: recipe_5_generate_image.md
plugins:
- glightbox
- include-markdown
theme:
  name: material
  favicon: media/favicon.png
  features:
  - navigation.instant
  - navigation.footer
  - content.code.copy
  - navigation.tabs.sticky
  - content.tabs.link
  font:
    code: Roboto Mono
    text: Roboto
  palette:
  - scheme: default
    primary: black
    accent: pink
    toggle:
      icon: material/brightness-2
      name: Switch to dark mode
  - scheme: slate
    primary: amber
    accent: cyan
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
markdown_extensions:
- toc:
    permalink: true
    toc_depth: 2
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- attr_list
- md_in_html
extra_css:
- css/custom.css
